### ISSUE TITLE
Datalayer support

### ISSUE THREAD

**Issue by j92** [tvlooy/GoogleTagManager#1]
Hi,

I am justing reading your code. I see it doesn't have support yet for the Datalayer. This could be usefull and I would like to add it. I am fairly new to Bolt, but I love it. You suggest to build a service so that you can push data from within the whole application. Its just not clear for me yet, can I create this service as a part of this extension? Could you push me a bit in the right direction, the rest I can figure out myself.

Oow, and I noticed that the tag is inserted at END_OF_HEAD, in the google documentation https://developers.google.com/tag-manager/quickstart is written that it should be right after the body tag. Can I also change that?

Cheers!

**Comment by tvlooy** [comment]
sure
